#!/bin/bash

# Deploys a serving component using an image generated by Seldon.
# Opens a port to the cluster for calling the service locally.

#PROJECT=${KF_DEV_PROJECT}
NAMESPACE=kubeflow
KF_ENV=default

#cd ks-kubeflow
cd ../../

# Generate component
ks generate seldon-serve-simple-v1alpha1 demo-test-serving \
  --name=demo-serving \
  --image=ysunglai/issue-summarization \
  --replicas=2

#You can directly use the jsonnet in the compoents


# Deploy it to cluster
ks apply ${KF_ENV} -c demo-test-serving

# Access from local machine
kubectl port-forward $(kubectl get pods -n ${NAMESPACE} -l service=ambassador -o jsonpath='{.items[0].metadata.name}') -n ${NAMESPACE} 8001:80

